services:
  remnawave-nginx:
    image: nginx:1.28
    container_name: remnawave-nginx
    hostname: remnawave-nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/remnabot_fullchain.pem:/etc/nginx/ssl/remnabot_fullchain.pem:ro
      - ./nginx/remnabot_privkey.key:/etc/nginx/ssl/remnabot_privkey.key:ro
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    networks:
      - remnawave-network
    depends_on:
      - remnashop

  remnashop-db:
    image: postgres:17
    container_name: "remnashop-db"
    hostname: remnashop-db
    restart: unless-stopped

    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - TZ=UTC
    
    volumes:
      - remnashop-db-data:/var/lib/postgresql/data
    networks:
      - remnawave-network

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 3s
      timeout: 10s
      retries: 3
    

  remnashop-redis:
    image: valkey/valkey:9-alpine
    container_name: "remnashop-redis"
    hostname: remnashop-redis
    restart: unless-stopped

    command: [ "--requirepass", "${REDIS_PASSWORD}" ]

    volumes:
      - remnashop-redis-data:/data

    networks:
      - remnawave-network

    healthcheck:
      test: ["CMD", "valkey-cli", "ping"]
      interval: 3s
      timeout: 10s
      retries: 3
    

  remnashop:
    &remnashop
    build:
      context: .
      dockerfile: Dockerfile.local
    image: remnashop:local
    container_name: "remnashop"
    hostname: remnashop
    restart: unless-stopped

    env_file:
      - .env
    environment:
      RESET_ASSETS: "${RESET_ASSETS:-false}"

    depends_on:
        remnashop-db:
          condition: service_healthy
        remnashop-redis:
          condition: service_healthy

    volumes:
      - ./logs:/opt/remnashop/logs
      - ./assets:/opt/remnashop/assets

    networks:
      - remnawave-network
    

  remnashop-taskiq-worker:
    image: remnashop:local
    container_name: "remnashop-taskiq-worker"
    hostname: remnashop-taskiq-worker
    restart: unless-stopped
    command: taskiq worker src.infrastructure.taskiq.worker:worker
      --tasks-pattern src/infrastructure/taskiq/tasks -fsd

    env_file:
      - .env
    environment:
      RESET_ASSETS: "${RESET_ASSETS:-false}"

    depends_on:
        remnashop:
          condition: service_started
        remnashop-redis:
          condition: service_healthy
        remnashop-db:
          condition: service_healthy

    volumes:
      - ./logs:/opt/remnashop/logs
      - ./assets:/opt/remnashop/assets

    networks:
      - remnawave-network


  remnashop-taskiq-scheduler:
    image: remnashop:local
    container_name: "remnashop-taskiq-scheduler"
    hostname: remnashop-taskiq-scheduler
    restart: unless-stopped
    command: taskiq scheduler src.infrastructure.taskiq.scheduler:scheduler
      --tasks-pattern src/infrastructure/taskiq/tasks -fsd

    env_file:
      - .env
    environment:
      RESET_ASSETS: "${RESET_ASSETS:-false}"

    depends_on:
        remnashop:
          condition: service_started
        remnashop-redis:
          condition: service_healthy
        remnashop-db:
          condition: service_healthy

    volumes:
      - ./logs:/opt/remnashop/logs
      - ./assets:/opt/remnashop/assets

    networks:
      - remnawave-network


networks:
  remnawave-network:
    name: remnawave-network 
    driver: bridge 
    external: false

volumes:
  remnashop-db-data:
    name: remnashop-db-data
    driver: local
    external: false
    
  remnashop-redis-data:
    name: remnashop-redis-data
    driver: local
    external: false
